### PR TITLE
Changed copy DDF, BinningHandler and getSimpleSummaryImpl 

### PR DESCRIPTION
**Pull request by shrutig**
Changed copy DDF, BinningHandler functions and getSimpleSummaryImpl function for proper working of these functionalities

### CODE REVIEW

**Comment by lebinh** [comment]
Can one of the admins verify this patch?

**Comment by hai-adatao** [comment]
@Huandao0812 @PangZhi @nhanitvn please help

**Comment by PangZhi** [comment]
I think the change has some problem when ddf itself is a view and stores query. Let me modify it. @hai-adatao @Huandao0812

**Comment by shrutig** [comment]
I have changed the maxJDBCPoolSize in ddf.ini which takes care of the timeout exception in the tests. @PangZhi please let me know the exact error you are talking about if you are still experiencing the same. Thanks.

**Comment by hai-adatao** [comment]
retest this please

**Pull request closed without merging**
